name: semantic-release-action
description: Action for workflow

inputs:
  token:
    description: ''
    required: true
  publish_token:
    description: ''
    required: true
  bot_name:
    description: ''
    required: true
  bot_email:
    description: ''
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - GITHUB_TOKEN=${{ inputs.token }}
    - NPM_TOKEN=${{ inputs.publish_token }}
    - GIT_AUTHOR_NAME=${{ inputs.bot_name }}
    - GIT_AUTHOR_EMAIL=${{ inputs.bot_email }}
